# Generated by Django 4.2.3 on 2023-11-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_chapter_chapterno_module_moduleno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='Draft', max_length=255),
        ),
    ]
