# Generated by Django 4.2.3 on 2023-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Personal Development', 'Personal Development'), ('Bioinformatics', 'Bioinformatics'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Music', 'Music')], max_length=255),
        ),
    ]
