# Generated by Django 4.2.3 on 2023-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
