# Generated by Django 4.2.3 on 2023-11-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
