# Generated by Django 4.2.3 on 2023-11-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
