# Generated by Django 4.2.3 on 2024-03-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_alter_order_purchase_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
