# Generated by Django 4.2.3 on 2024-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_ratingview_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='course_completed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
