# Generated by Django 4.2.3 on 2024-03-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_ratingview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='course',
        ),
    ]
