# Generated by Django 4.2.3 on 2024-03-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_learning_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='course_completed',
        ),
    ]
